#!/bin/sh
# Shared config for the OpenWrt QEMU harness. Sourced by the other scripts.
# POSIX sh; runs on the macOS host (not in the VM).
set -eu

VM_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$VM_DIR/../.." && pwd)

IMAGES="$VM_DIR/images"
RUN="$VM_DIR/run"           # per-run mutable state (disk, sockets, logs, pidfile)

OPENWRT_VER="24.10.3"
IMG_BASE="openwrt-${OPENWRT_VER}-armsr-armv8-generic-ext4-combined-efi"
IMG_URL="https://downloads.openwrt.org/releases/${OPENWRT_VER}/targets/armsr/armv8/${IMG_BASE}.img.gz"
IMG_GZ="$IMAGES/${IMG_BASE}.img.gz"
IMG_RAW="$IMAGES/${IMG_BASE}.img"     # pristine, never booted directly
DISK="$RUN/disk.qcow2"                # per-run overlay (qcow2 backed by IMG_RAW)

# edk2 UEFI firmware shipped by brew qemu.
EFI_CODE_SRC="/opt/homebrew/share/qemu/edk2-aarch64-code.fd"
EFI_VARS_SRC="/opt/homebrew/share/qemu/edk2-arm-vars.fd"
EFI_CODE="$RUN/edk2-code.fd"
EFI_VARS="$RUN/edk2-vars.fd"

SERIAL_SOCK="$RUN/serial.sock"
MON_SOCK="$RUN/monitor.sock"
PIDFILE="$RUN/vm.pid"
SERIAL_LOG="$RUN/serial.log"

SSH_PORT=2222
SSH_HOST=127.0.0.1
SSH_KEY="$RUN/id_vmtest"              # generated by provision.sh
VM_MEM=512
VM_SMP=2

# ssh opts: no host-key churn between runs, fast fail.
VM_SSH_OPTS="-p $SSH_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-o ConnectTimeout=8 -o BatchMode=yes -o LogLevel=ERROR -i $SSH_KEY"

vm_log() { echo "[vm] $*" >&2; }
